### ISSUE TITLE
组织、用户和行政班的关系讨论

### ISSUE THREAD

**Issue by AirboZH** [HXTIA/workboard_backend#59]
如果是现在组织和用户一对多的关系，那么行政班和组织的关系就很尴尬了。
- 如果绑定组织和行政班一对多的话，用户和行政班还需要一个多对一的关系
- 如果用户和行政班多对一的话，又缺少了组织和行政班的关系

![image](https://user-images.githubusercontent.com/50261327/218298569-b471cfb6-9c48-4db5-aed0-7f0e1b5bfa30.png)

**我觉得行政班的所属组织的关系是绑定的，但用户和组织的关系是灵活的**
- 如果去除用户和组织的关系，通过加入行政班的方式来加入组织。既可以通过加入行政班的方式关联到组织。也可以保证组织和行政班的从属关系。

![image](https://user-images.githubusercontent.com/50261327/218298627-2d3014fd-ebb1-43ac-8991-166c291f6881.png)

以上想法可能需要将user表的org_id字段移动到clazz表，至于多组织，可以通过加入多个行政班来解决。
@YellowOrangee @Yziyan

**Comment by Yziyan** [comment]
“我觉得行政班的所属组织的关系是绑定的，但用户和组织的关系是灵活的”，这个有道理。
这样做也行。感觉这样还挺合理的。因为行政班肯定是属于一个组织的。然后用户又和行政班强绑定。就间接和组织绑定了。也可以拿到组织信息！！👍
